CREATE TABLE boat (
  id INT AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  coord_x INT NOT NULL,
  coord_y INT NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE tile (
  id INT AUTO_INCREMENT NOT NULL,
  type VARCHAR(255) NOT NULL,
  coord_x INT NOT NULL,
  coord_y INT NOT NULL,
  has_treasure BOOLEAN DEFAULT FALSE,
  PRIMARY KEY(id)
);

INSERT INTO boat (name, coord_x, coord_y)
VALUES
  ("Black Pearl", 1, 1),
  ("Flying Dutchman", 4, 5),
  ("Queen Anne's Revenge", 10, 4),
  ("The Walrus", 9, 0);

INSERT INTO tile (type, coord_x, coord_y, has_treasure) 
VALUES 
  ("sea", 0, 0, false), 
  ("sea", 1, 0, false), 
  ("sea", 2, 0, false), 
  ("sea", 3, 0, false), 
  ("sea", 4, 0, false), 
  ("island", 5, 0, false), 
  ("sea", 6, 0, false), 
  ("sea", 7, 0, false), 
  ("sea", 8, 0, false), 
  ("port", 9, 0, false), 
  ("sea", 10, 0, false), 
  ("sea", 11, 0, false), 
  ("sea", 0, 1, false), 
  ("port", 1, 1, false), 
  ("sea", 2, 1, false),
  ("island", 3, 1, false), 
  ("sea", 4, 1, false), 
  ("sea", 5, 1, false), 
  ("sea", 6, 1, false), 
  ("sea", 7, 1, false), 
  ("sea", 8, 1, false), 
  ("sea", 9, 1, false), 
  ("island", 10, 1, false), 
  ("sea", 11, 1, false), 
  ("sea", 0, 2, false), 
  ("sea", 1, 2, false), 
  ("sea", 2, 2, false), 
  ("sea", 3, 2, false), 
  ("sea", 4, 2, false), 
  ("sea", 5, 2, false), 
  ("sea", 6, 2, false), 
  ("sea", 7, 2, false), 
  ("island", 8, 2, false), 
  ("sea", 9, 2, false), 
  ("sea", 10, 2, false), 
  ("sea", 11, 2, false), 
  ("sea", 0, 3, false), 
  ("island", 1, 3, false), 
  ("sea", 2, 3, false), 
  ("sea", 3, 3, false), 
  ("island", 4, 3, false), 
  ("sea", 5, 3, false), 
  ("sea", 6, 3, false), 
  ("sea", 7, 3, false), 
  ("sea", 8, 3, false), 
  ("sea", 9, 3, false), 
  ("sea", 10, 3, false), 
  ("sea", 11, 3, false), 
  ("sea", 0, 4, false), 
  ("sea", 1, 4, false), 
  ("sea", 2, 4, false), 
  ("sea", 3, 4, false), 
  ("sea", 4, 4, false), 
  ("sea", 5, 4, false), 
  ("sea", 6, 4, false), 
  ("island", 7, 4, false), 
  ("sea", 8, 4, false), 
  ("sea", 9, 4, false), 
  ("port", 10, 4, false), 
  ("sea", 11, 4, false), 
  ("island", 0, 5, false), 
  ("sea", 1, 5, false), 
  ("sea", 2, 5, false), 
  ("sea", 3, 5, false), 
  ("port", 4, 5, false), 
  ("sea", 5, 5, false), 
  ("sea", 6, 5, false), 
  ("sea", 7, 5, false), 
  ("sea", 8, 5, false), 
  ("sea", 9, 5, false), 
  ("sea", 10, 5, false), 
  ("island", 11, 5, false);
